// Auto-generated by scripts/set-version.mjs — do not edit manually
export const buildInfo = {
  version: '1.0.0',
  commitHash: '36b4bc5',
  commitMessage: 'Add Photos area — auth-gated uploads with masonry gallery',
  commitDate: '2026-03-30 11:43:10 +0100',
  buildDate: '2026-03-30T11:06:33.029Z',
};
