// Auto-generated by scripts/set-version.mjs — do not edit manually
export const buildInfo = {
  version: '1.0.0',
  commitHash: '13e3b0d',
  commitMessage: 'Add One-off / Periodic flag to Costs items',
  commitDate: '2026-09-03 13:06:43 +0100',
  buildDate: '2026-09-03T12:32:52.049Z',
};
