import { execSync } from 'child_process';
import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

function git(cmd) {
  try {
    return execSync(cmd, { cwd: root }).toString().trim();
  } catch {
    return '';
  }
}

const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'));

const info = {
  version: pkg.version,
  commitHash: git('git rev-parse --short HEAD'),
  commitMessage: git('git log -1 --pretty=%s'),
  commitDate: git('git log -1 --pretty=%ci'),
  buildDate: new Date().toISOString(),
};

const escaped = (s) => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/`/g, '\\`');

const content = `// Auto-generated by scripts/set-version.mjs — do not edit manually
export const buildInfo = {
  version: '${escaped(info.version)}',
  commitHash: '${escaped(info.commitHash)}',
  commitMessage: '${escaped(info.commitMessage)}',
  commitDate: '${escaped(info.commitDate)}',
  buildDate: '${escaped(info.buildDate)}',
};
`;

writeFileSync(resolve(root, 'src/app/build-info.ts'), content);
console.log(`[set-version] v${info.version} · ${info.commitHash} · ${info.commitMessage}`);
